
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView Tiempo;

	private global::Gtk.Label texto;

	private global::Gtk.Image image1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.Tiempo = new global::Gtk.TextView();
		this.Tiempo.Buffer.Text = global::Mono.Unix.Catalog.GetString("00:00");
		this.Tiempo.CanFocus = true;
		this.Tiempo.Name = "Tiempo";
		this.Tiempo.Justification = ((global::Gtk.Justification)(2));
		this.GtkScrolledWindow.Add(this.Tiempo);
		this.hbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
		w2.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.texto = new global::Gtk.Label();
		this.texto.Name = "texto";
		this.texto.LabelProp = global::Mono.Unix.Catalog.GetString("cambiame");
		this.hbox1.Add(this.texto);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.texto]));
		w3.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.image1 = new global::Gtk.Image();
		this.image1.Name = "image1";
		this.hbox1.Add(this.image1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.image1]));
		w4.Position = 2;
		this.Add(this.hbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
